POST http://localhost:3000/users
Content-Type: application/json
{
  "firstName": "#FC#",
"lastName": "kjlhl",
  "email": "mjolskffffdfddhsfkjkjlkjjioiuljkujkhjplkjp519@gmail.com",
  "password": "33#$%@fd42423"
}


POST http://localhost:3000/users/create-many
Content-Type: application/json
{
  "users": [
  
{ 
  "firstName": "kareem",
  "lastName": "benzime",
  "email": "test@test.com",
  "password": "@Password123"
},

{
  "firstName": "kareem",
  "lastName": "benzime",
  "email": "test@test.com",
  "password": "@Password123"
},

{
  "firstName": "kareem",
  "lastName": "benzime",
  "email": "test@test.com",
  "password": "@Password123"
}
]



}