POST http://localhost:3000/tags/
Content-Type: application/json

{
  "name": "NestJs",
  "slug": "nestjs",
  "description": "NestJs is a progressive Node.js framework for building efficient and scalable server-side applications."
}